CREATE DATABASE POC_Database;

USE POC_Database;

CREATE TABLE ncm_entries(
	id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	[user] VARCHAR(MAX) NOT NULL,
	ipi VARCHAR(MAX),
	ncm VARCHAR(MAX) NOT NULL,
	[description] TEXT NOT NULL,
	created_at DATETIME2(3) NOT NULL
);